name: Update tag

on:
  push:
    tags: [ v* ]

jobs:

  update-tag:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - name: Update version in source
      run: |
        cat ./shjp |
        awk '{if(NR==2){print "version='${{ github.ref_name }}'"}else{print $0}}' > ./temp
        cat ./temp > ./shjp
        rm ./temp

    - name: Push
      run: |
        git add . 
        git commit -m "update version" 
        git push origin main

    - name: Merge to develop
      run: |
        git fetch
        git checkout develop
        git merge main
        git push origin develop

    - name: Update tag
      run: |
        version=${{ github.ref_name }}
        git tag -d ${version%%.*}
        git tag -a ${version%%.*} -m "BY-CI"
        git push origin ${version%%.*} -f

    - name: Post tweet
      run: |
        ./.github/workflows/sh/tweet_template.sh \
        ${{ github.ref_name }} \
        ${{ github.event.repository.html_url }} > ./data_temp
        ./.github/workflows/sh/tweet.sh \
        ${{ secrets.TW_CONS_KEY }} \
        ${{ secrets.TW_CONS_SECRET }} \
        ${{ secrets.TW_OAUTH_TOKEN }} \
        ${{ secrets.TW_OAUTH_SECRET }} \
        ./data_temp

