name: Test by sync PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]
    paths:
      - 'shjp.sh'
      - 'bbtdef.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - name: Update submodules
      run: git submodule update --remote

    - name: Test
      run: ./cmdbbt/start.sh
